#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Xamarin.FloatLabeledEditText.Resource", IsApplication=false)]

namespace Xamarin.FloatLabeledEditText
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010006
			public static int fletBackground = 2130771974;
			
			// aapt resource value: 0x7f010001
			public static int fletPadding = 2130771969;
			
			// aapt resource value: 0x7f010005
			public static int fletPaddingBottom = 2130771973;
			
			// aapt resource value: 0x7f010002
			public static int fletPaddingLeft = 2130771970;
			
			// aapt resource value: 0x7f010004
			public static int fletPaddingRight = 2130771972;
			
			// aapt resource value: 0x7f010003
			public static int fletPaddingTop = 2130771971;
			
			// aapt resource value: 0x7f010000
			public static int fletTextAppearance = 2130771968;
			
			// aapt resource value: 0x7f010007
			public static int fletUseAccentColor = 2130771975;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FloatLabeledEditText = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975};
			
			// aapt resource value: 6
			public static int FloatLabeledEditText_fletBackground = 6;
			
			// aapt resource value: 1
			public static int FloatLabeledEditText_fletPadding = 1;
			
			// aapt resource value: 5
			public static int FloatLabeledEditText_fletPaddingBottom = 5;
			
			// aapt resource value: 2
			public static int FloatLabeledEditText_fletPaddingLeft = 2;
			
			// aapt resource value: 4
			public static int FloatLabeledEditText_fletPaddingRight = 4;
			
			// aapt resource value: 3
			public static int FloatLabeledEditText_fletPaddingTop = 3;
			
			// aapt resource value: 0
			public static int FloatLabeledEditText_fletTextAppearance = 0;
			
			// aapt resource value: 7
			public static int FloatLabeledEditText_fletUseAccentColor = 7;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
