#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SampleApp.Resource", IsApplication=true)]

namespace SampleApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.FloatLabeledEditText.Resource.Attribute.fletBackground = global::SampleApp.Resource.Attribute.fletBackground;
			global::Xamarin.FloatLabeledEditText.Resource.Attribute.fletPadding = global::SampleApp.Resource.Attribute.fletPadding;
			global::Xamarin.FloatLabeledEditText.Resource.Attribute.fletPaddingBottom = global::SampleApp.Resource.Attribute.fletPaddingBottom;
			global::Xamarin.FloatLabeledEditText.Resource.Attribute.fletPaddingLeft = global::SampleApp.Resource.Attribute.fletPaddingLeft;
			global::Xamarin.FloatLabeledEditText.Resource.Attribute.fletPaddingRight = global::SampleApp.Resource.Attribute.fletPaddingRight;
			global::Xamarin.FloatLabeledEditText.Resource.Attribute.fletPaddingTop = global::SampleApp.Resource.Attribute.fletPaddingTop;
			global::Xamarin.FloatLabeledEditText.Resource.Attribute.fletTextAppearance = global::SampleApp.Resource.Attribute.fletTextAppearance;
			global::Xamarin.FloatLabeledEditText.Resource.Styleable.FloatLabeledEditText = global::SampleApp.Resource.Styleable.FloatLabeledEditText;
			global::Xamarin.FloatLabeledEditText.Resource.Styleable.FloatLabeledEditText_fletBackground = global::SampleApp.Resource.Styleable.FloatLabeledEditText_fletBackground;
			global::Xamarin.FloatLabeledEditText.Resource.Styleable.FloatLabeledEditText_fletPadding = global::SampleApp.Resource.Styleable.FloatLabeledEditText_fletPadding;
			global::Xamarin.FloatLabeledEditText.Resource.Styleable.FloatLabeledEditText_fletPaddingBottom = global::SampleApp.Resource.Styleable.FloatLabeledEditText_fletPaddingBottom;
			global::Xamarin.FloatLabeledEditText.Resource.Styleable.FloatLabeledEditText_fletPaddingLeft = global::SampleApp.Resource.Styleable.FloatLabeledEditText_fletPaddingLeft;
			global::Xamarin.FloatLabeledEditText.Resource.Styleable.FloatLabeledEditText_fletPaddingRight = global::SampleApp.Resource.Styleable.FloatLabeledEditText_fletPaddingRight;
			global::Xamarin.FloatLabeledEditText.Resource.Styleable.FloatLabeledEditText_fletPaddingTop = global::SampleApp.Resource.Styleable.FloatLabeledEditText_fletPaddingTop;
			global::Xamarin.FloatLabeledEditText.Resource.Styleable.FloatLabeledEditText_fletTextAppearance = global::SampleApp.Resource.Styleable.FloatLabeledEditText_fletTextAppearance;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010006
			public const int fletBackground = 2130771974;
			
			// aapt resource value: 0x7f010001
			public const int fletPadding = 2130771969;
			
			// aapt resource value: 0x7f010005
			public const int fletPaddingBottom = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int fletPaddingLeft = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int fletPaddingRight = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int fletPaddingTop = 2130771971;
			
			// aapt resource value: 0x7f010000
			public const int fletTextAppearance = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int floatlabelededittext = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FloatLabeledEditText = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974};
			
			// aapt resource value: 6
			public const int FloatLabeledEditText_fletBackground = 6;
			
			// aapt resource value: 1
			public const int FloatLabeledEditText_fletPadding = 1;
			
			// aapt resource value: 5
			public const int FloatLabeledEditText_fletPaddingBottom = 5;
			
			// aapt resource value: 2
			public const int FloatLabeledEditText_fletPaddingLeft = 2;
			
			// aapt resource value: 4
			public const int FloatLabeledEditText_fletPaddingRight = 4;
			
			// aapt resource value: 3
			public const int FloatLabeledEditText_fletPaddingTop = 3;
			
			// aapt resource value: 0
			public const int FloatLabeledEditText_fletTextAppearance = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
